# Generated by Django 6.0.4 on 2026-08-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_teacher_approved',
            field=models.BooleanField(default=False),
        ),
    ]
