# Generated by Django 6.0.4 on 2026-07-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_duration_lesson_lesson_pdf_lesson_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
    ]
