# Generated by Django 6.0.4 on 2026-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_video_url_lesson_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='lesson_videos/'),
        ),
    ]
