from django.urls import path
from . import views

urlpatterns = [

    path(
        "add-course/",
        views.add_course,
        name="add_course"
    ),
    path(
        "my-courses/",
        views.my_courses,
        name="my_courses"
    ),
    path(
    "edit-course/<int:course_id>/",
    views.edit_course,
    name="edit_course"
    ),
    path(
    "delete-course/<int:course_id>/",
    views.delete_course,
    name="delete_course"
    ),
    path(
    "courses/",
    views.course_list,
    name="course_list"
    ),
    path(
    "course/<int:course_id>/",
    views.course_detail,
    name="course_detail"
    ),
    path(
    "enroll/<int:course_id>/",
    views.enroll_course,
    name="enroll_course"
    ),
    path(
    "my-learning/",
    views.my_learning,
    name="my_learning"
    ),
    path(
    "add-lesson/<int:course_id>/",
    views.add_lesson,
    name="add_lesson"
    ),
    path(
    "lesson/<int:lesson_id>/",
    views.lesson_detail,
    name="lesson_detail"
    ),
    path(
    "lesson/<int:lesson_id>/complete/",
    views.mark_complete,
    name="mark_complete"
    ),
    path(
    "lesson/<int:lesson_id>/add-quiz/",
    views.add_quiz,
    name="add_quiz"
    ),
    path(
    "quiz/<int:quiz_id>/submit/",
    views.submit_quiz,
    name="submit_quiz"
    ),
    path(
    "quiz-history/",
    views.quiz_history,
    name="quiz_history"
    ),
    path(
    "course/<int:course_id>/certificate/",
    views.download_certificate,
    name="download_certificate"
    ),
    path(
    "lesson/<int:lesson_id>/edit/",
    views.edit_lesson,
    name="edit_lesson"
    ),
   path(
    "lesson/<int:lesson_id>/delete/",
    views.delete_lesson,
    name="delete_lesson"
    ),
    path(
    "quiz/<int:quiz_id>/edit/",
    views.edit_quiz,
    name="edit_quiz"
    ),
    path(
    "quiz/<int:quiz_id>/delete/",
    views.delete_quiz,
    name="delete_quiz"
    ),
    path(
    "my-enrolled-courses/",
    views.my_enrolled_courses,
    name="my_enrolled_courses"
    ),
    path(
    "continue-learning/<int:course_id>/",
    views.continue_learning,
    name="continue_learning"
    ),
    path(
    "certificate-center/",
    views.certificate_center,
    name="certificate_center"
    ),
    path(
    "course/<int:course_id>/add-live-class/",
    views.add_live_class,
    name="add_live_class"
    ),
    path(
    "live-class/<int:live_class_id>/edit/",
    views.edit_live_class,
    name="edit_live_class"
    ),
    path(
    "live-class/<int:live_class_id>/delete/",
    views.delete_live_class,
    name="delete_live_class"
    ),
    path(
    "join-live-class/<int:live_class_id>/",
    views.join_live_class,
    name="join_live_class"
    ),
    path(
    "live-class/<int:live_class_id>/attendance/",
    views.view_attendance,
    name="view_attendance"
    ),
    path(
    "course/<int:course_id>/add-assignment/",
    views.add_assignment,
    name="add_assignment"
    ),
    path(
    "assignment/<int:assignment_id>/submit/",
    views.submit_assignment,
    name="submit_assignment"
    ),
    path(
    "assignment/<int:assignment_id>/submissions/",
    views.view_submissions,
    name="view_submissions"
    ),
    path(
    "submission/<int:submission_id>/grade/",
    views.grade_submission,
    name="grade_submission"
    ),
    path(
    "course/<int:course_id>/payment/",
    views.course_payment,
    name="course_payment"
    ),
    path(
    "payment-verify/",
    views.payment_verify,
    name="payment_verify"
    ),
    path(
    "about/",
    views.about,
    name="about"
    ),
    path(
    "contact/",
    views.contact,
    name="contact"
    ),
    path(
    "my-students/",
    views.my_students,
    name="my_students"
    ),
    path(
    "teacher-payments/",
    views.teacher_payments,
    name="teacher_payments"
    ),

]